spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5435/kampusX
spring.datasource.username=postgres
spring.datasource.password=Yuvi2411@jind
server.port=8081
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true